# Generated by Django 4.2.4 on 2023-09-28 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_exercise_completedexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexercise',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='CompletedExercise',
        ),
    ]
